"""Add auto_replies and media_files

Revision ID: 9aef5616e35e
Revises: d2df2a419a56
Create Date: 2026-01-17 17:25:22.279321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aef5616e35e'
down_revision: Union[str, Sequence[str], None] = 'd2df2a419a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_table('auto_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'CONTAINS', 'REGEX', name='matchtype'), nullable=False),
    sa.Column('reply_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'LOCATION', 'STICKER', 'FLEX', 'TEMPLATE', 'IMAGEMAP', name='replytype'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_replies_id'), 'auto_replies', ['id'], unique=False)
    op.create_index(op.f('ix_auto_replies_keyword'), 'auto_replies', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_replies_keyword'), table_name='auto_replies')
    op.drop_index(op.f('ix_auto_replies_id'), table_name='auto_replies')
    op.drop_table('auto_replies')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
