"""Add reply_objects table

Revision ID: cd2257cee794
Revises: 9aef5616e35e
Create Date: 2026-01-17 17:47:28.793021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd2257cee794'
down_revision: Union[str, Sequence[str], None] = '9aef5616e35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('object_type', sa.Enum('TEXT', 'FLEX', 'IMAGE', 'STICKER', 'VIDEO', 'AUDIO', 'LOCATION', 'IMAGEMAP', name='objecttype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alt_text', sa.String(length=400), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_objects_id'), 'reply_objects', ['id'], unique=False)
    op.create_index(op.f('ix_reply_objects_object_id'), 'reply_objects', ['object_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_objects_object_id'), table_name='reply_objects')
    op.drop_index(op.f('ix_reply_objects_id'), table_name='reply_objects')
    op.drop_table('reply_objects')
    # ### end Alembic commands ###
